
INCLUDE(TestBigEndian)
INCLUDE(DetectGcc)

# endianness
TEST_BIG_ENDIAN(BIG_ENDIAN)
SET(ENDIAN_FLAGS " -DLITTLE_ENDIAN -DBYTE_ORDER=4321 " )
IF(BIG_ENDIAN)
  SET(ENDIAN_FLAGS " -DBIG_ENDIAN -DBYTE_ORDER=1234 " )
ENDIF(BIG_ENDIAN)

SET(PLATFORM_FLAGS "")

IF(UNIX)
  SET(PLATFORM_FLAGS " ${PLATFORM_FLAGS} -DUNIX ")
ENDIF(UNIX)

IF(APPLE)
  SET(PLATFORM_FLAGS " ${PLATFORM_FLAGS} -DAPPLE ")
ENDIF(APPLE)

IF(MSVC)
  SET(PLATFORM_FLAGS " ${PLATFORM_FLAGS} -DMSVC ")
ENDIF(MSVC)

IF(CMAKE_SYSTEM_NAME MATCHES "Linux")
  SET(PLATFORM_FLAGS " ${PLATFORM_FLAGS} -DLINUX -D_POSIX_C_SOURCE=199506L")
ENDIF(CMAKE_SYSTEM_NAME MATCHES "Linux")

IF(CMAKE_SYSTEM_NAME MATCHES "FreeBSD")
  SET(PLATFORM_FLAGS " ${PLATFORM_FLAGS} -DFREEBSD ")
ENDIF(CMAKE_SYSTEM_NAME MATCHES "FreeBSD")

# common logger flags
# SET(LOGFLAGS " -DLOG_INFO_ENABLED -DLOG_ERROR_ENABLED -DLOG_TRACE_ENABLED -DLOG_SCOPED_TRACE_ENABLED -DLOG_LOGGER_LOCATION_SETTING_ENABLED -DLOG_SET_TRACE_DISABLED_BY_DEFAULT ")
SET(LOGFLAGS " ")

SET(COMMON_CXX_FLAGS " ${PLATFORM_FLAGS} ${ENDIAN_FLAGS} ${LOGFLAGS} ")
SET(COMMON_C_FLAGS " ${PLATFORM_FLAGS} ${ENDIAN_FLAGS} ")

SET(CMAKE_C_FLAGS_DEBUG " ${GCC_C_FLAGS_DEBUG} ${COMMON_C_FLAGS} ")
SET(CMAKE_C_FLAGS_RELEASE " ${GCC_C_FLAGS_RELEASE} ${COMMON_C_FLAGS} -DNDEBUG ")
SET(CMAKE_C_FLAGS_PROFILE " ${GCC_C_FLAGS_PROFILE} ${COMMON_C_FLAGS} ")

SET(CMAKE_CXX_FLAGS_DEBUG " ${GCC_CXX_FLAGS_DEBUG} ${COMMON_CXX_FLAGS} ")
SET(CMAKE_CXX_FLAGS_RELEASE " ${GCC_CXX_FLAGS_RELEASE} ${COMMON_CXX_FLAGS} -DNDEBUG ")
SET(CMAKE_CXX_FLAGS_PROFILE " ${GCC_CXX_FLAGS_PROFILE} ${COMMON_CXX_FLAGS} ")

# default is debug configuration
SET(CMAKE_C_FLAGS ${CMAKE_C_FLAGS_DEBUG})
SET(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS_DEBUG})

# change config if release
IF(CMAKE_BUILD_TYPE MATCHES "release")
  SET(CMAKE_C_FLAGS ${CMAKE_C_FLAGS_RELEASE})
  SET(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS_RELEASE})
ENDIF(CMAKE_BUILD_TYPE MATCHES "release")

# change config if profile
IF(CMAKE_BUILD_TYPE MATCHES "profile")
  SET(CMAKE_C_FLAGS ${CMAKE_C_FLAGS_PROFILE})
  SET(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS_PROFILE})
ENDIF(CMAKE_BUILD_TYPE MATCHES "profile")

MESSAGE(STATUS "Build type: " ${CMAKE_BUILD_TYPE})
MESSAGE(STATUS "C FLAGS:    " ${CMAKE_C_FLAGS})
MESSAGE(STATUS "CXX FLAGS:  " ${CMAKE_CXX_FLAGS})
