MESSAGE(STATUS "Detecting iconv")

FIND_PATH(ICONV_INCLUDE_DIR iconv.h
  PATHS /opt/local/include /opt/include /usr/local/include /usr/include /sw/include )

FIND_LIBRARY(ICONV_LIBRARY NAMES libiconv.a iconv.a iconv
  PATH_SUFFIXES lib64 lib
  PATHS /opt/local /opt /usr/local /usr /sw )

SET(ICONV_FOUND "NO")

IF(ICONV_INCLUDE_DIR AND ICONV_LIBRARY)
   SET(ICONV_FOUND TRUE)
ELSE(ICONV_INCLUDE_DIR AND ICONV_LIBRARY)
   UNSET(ICONV_LIBRARY)
   UNSET(ICONV_INCLUDE_DIR)
ENDIF(ICONV_INCLUDE_DIR AND ICONV_LIBRARY)

IF(ICONV_FOUND)
  MESSAGE(STATUS "  OK : iconv lib: ${ICONV_LIBRARY}")
  MESSAGE(STATUS "  OK : iconv inc: ${ICONV_INCLUDE_DIR}")
ELSE(ICONV_FOUND)
  MESSAGE(STATUS "! KO : iconv NOT found")
ENDIF(ICONV_FOUND)

