
IF(PG_FOUND)
  MESSAGE(STATUS "Setting up Postgres compatible linker flags")
  SET(CMAKE_MODULE_LINKER_FLAGS "-fPIC")
  SET(CMAKE_SHARED_LINKER_FLAGS "-fPIC")
  SET(CMAKE_EXE_LINKER_FLAGS "-fPIC")
ENDIF(PG_FOUND)

