
IF(PG_FOUND)
  MESSAGE(STATUS "Setting up Postgres compatible compiler flags")
  SET(OLD_C_FLAGS ${CMAKE_C_FLAGS})
  SET(OLD_CXX_FLAGS ${CMAKE_CXX_FLAGS})
  SET(CMAKE_C_FLAGS "${OLD_C_FLAGS} -fPIC -DPG_VARHDR_SIZE=4")
  SET(CMAKE_CXX_FLAGS "${OLD_CXX_FLAGS} -fPIC -DPG_VARHDR_SIZE=4")
  MESSAGE(STATUS "  new CFLAGS: ${CMAKE_C_FLAGS}")
  MESSAGE(STATUS "  new CXXFLAGS: ${CMAKE_CXX_FLAGS}")
ENDIF(PG_FOUND)

